package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1



/**
 * AdminLogin generated by hbm2java
 */
public class AdminLogin  implements java.io.Serializable {


     private String adminLoginId;
     private String adminPassword;

    public AdminLogin() {
    }

    public AdminLogin(String adminLoginId, String adminPassword) {
       this.adminLoginId = adminLoginId;
       this.adminPassword = adminPassword;
    }
   
    public String getAdminLoginId() {
        return this.adminLoginId;
    }
    
    public void setAdminLoginId(String adminLoginId) {
        this.adminLoginId = adminLoginId;
    }
    public String getAdminPassword() {
        return this.adminPassword;
    }
    
    public void setAdminPassword(String adminPassword) {
        this.adminPassword = adminPassword;
    }




}


