package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * CitySport generated by hbm2java
 */
public class CitySport  implements java.io.Serializable {


     private Integer cityId;
     private String cityName;
     private Boolean cityStatus;
     private Date cityDate;
     private Set venues = new HashSet(0);

    public CitySport() {
    }

	
//    public CitySport(String cityName) {
//        this.cityName = cityName;
//    }
    public CitySport(String cityName, Boolean cityStatus, Date cityDate) {
        this.cityName = cityName;
        this.cityStatus = cityStatus;
        this.cityDate = cityDate;
    }
    
    
    public CitySport(String cityName, Boolean cityStatus, Date cityDate, Set venues) {
       this.cityName = cityName;
       this.cityStatus = cityStatus;
       this.cityDate = cityDate;
       this.venues = venues;
    }
   
    public Integer getCityId() {
        return this.cityId;
    }
    
    public void setCityId(Integer cityId) {
        this.cityId = cityId;
    }
    public String getCityName() {
        return this.cityName;
    }
    
    public void setCityName(String cityName) {
        this.cityName = cityName;
    }
    public Boolean getCityStatus() {
        return this.cityStatus;
    }
    
    public void setCityStatus(Boolean cityStatus) {
        this.cityStatus = cityStatus;
    }
    public Date getCityDate() {
        return this.cityDate;
    }
    
    public void setCityDate(Date cityDate) {
        this.cityDate = cityDate;
    }
    public Set getVenues() {
        return this.venues;
    }
    
    public void setVenues(Set venues) {
        this.venues = venues;
    }
}


