package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * CityMaster generated by hbm2java
 */
public class CityMaster  implements java.io.Serializable {


     private Integer ctid;
     private StateMaster stateMaster;
     private String ctname;
     private Set userses = new HashSet(0);

    public CityMaster() {
    }

	
    public CityMaster(StateMaster stateMaster, String ctname) {
        this.stateMaster = stateMaster;
        this.ctname = ctname;
    }
    public CityMaster(StateMaster stateMaster, String ctname, Set userses) {
       this.stateMaster = stateMaster;
       this.ctname = ctname;
       this.userses = userses;
    }
   
    public Integer getCtid() {
        return this.ctid;
    }
    
    public void setCtid(Integer ctid) {
        this.ctid = ctid;
    }
    public StateMaster getStateMaster() {
        return this.stateMaster;
    }
    
    public void setStateMaster(StateMaster stateMaster) {
        this.stateMaster = stateMaster;
    }
    public String getCtname() {
        return this.ctname;
    }
    
    public void setCtname(String ctname) {
        this.ctname = ctname;
    }
    public Set getUserses() {
        return this.userses;
    }
    
    public void setUserses(Set userses) {
        this.userses = userses;
    }
}


