package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1



/**
 * OtpMaster generated by hbm2java
 */
public class OtpMaster  implements java.io.Serializable {


     private int userId;
     private Users users;
     private int otpNo;

    public OtpMaster() {
    }

    public OtpMaster(Users users, int otpNo) {
       this.users = users;
       this.otpNo = otpNo;
    }
   
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }
    public Users getUsers() {
        return this.users;
    }
    
    public void setUsers(Users users) {
        this.users = users;
    }
    public int getOtpNo() {
        return this.otpNo;
    }
    
    public void setOtpNo(int otpNo) {
        this.otpNo = otpNo;
    }




}


