package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Sport generated by hbm2java
 */
public class Sport  implements java.io.Serializable {


     private Integer sportId;
     private String sportName;
     private Set venueSports = new HashSet(0);

    public Sport() {
    }

	
    public Sport(String sportName) {
        this.sportName = sportName;
    }
    public Sport(String sportName, Set venueSports) {
       this.sportName = sportName;
       this.venueSports = venueSports;
    }
   
    public Integer getSportId() {
        return this.sportId;
    }
    
    public void setSportId(Integer sportId) {
        this.sportId = sportId;
    }
    public String getSportName() {
        return this.sportName;
    }
    
    public void setSportName(String sportName) {
        this.sportName = sportName;
    }
    public Set getVenueSports() {
        return this.venueSports;
    }
    
    public void setVenueSports(Set venueSports) {
        this.venueSports = venueSports;
    }
}


