package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * StateMaster generated by hbm2java
 */
public class StateMaster  implements java.io.Serializable {


     private Integer sid;
     private String sname;
     private Set cityMasters = new HashSet(0);

    public StateMaster() {
    }

	
    public StateMaster(String sname) {
        this.sname = sname;
    }
    public StateMaster(String sname, Set cityMasters) {
       this.sname = sname;
       this.cityMasters = cityMasters;
    }
   
    public Integer getSid() {
        return this.sid;
    }
    
    public void setSid(Integer sid) {
        this.sid = sid;
    }
    public String getSname() {
        return this.sname;
    }
    
    public void setSname(String sname) {
        this.sname = sname;
    }
    public Set getCityMasters() {
        return this.cityMasters;
    }
    
    public void setCityMasters(Set cityMasters) {
        this.cityMasters = cityMasters;
    }
}


