package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * TaxMaster generated by hbm2java
 */
public class TaxMaster  implements java.io.Serializable {


     private Integer taxId;
     private float taxPrice;
     private boolean taxStatus;
     private Date taxDate;

    public TaxMaster() {
    }

    public TaxMaster(float taxPrice, boolean taxStatus, Date taxDate) {
       this.taxPrice = taxPrice;
       this.taxStatus = taxStatus;
       this.taxDate = taxDate;
    }
   
    public Integer getTaxId() {
        return this.taxId;
    }
    
    public void setTaxId(Integer taxId) {
        this.taxId = taxId;
    }
    public float getTaxPrice() {
        return this.taxPrice;
    }
    
    public void setTaxPrice(float taxPrice) {
        this.taxPrice = taxPrice;
    }
    public boolean isTaxStatus() {
        return this.taxStatus;
    }
    
    public void setTaxStatus(boolean taxStatus) {
        this.taxStatus = taxStatus;
    }
    public Date getTaxDate() {
        return this.taxDate;
    }
    
    public void setTaxDate(Date taxDate) {
        this.taxDate = taxDate;
    }




}


