package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Users generated by hbm2java
 */
public class Users  implements java.io.Serializable {


     private Integer id;
     private CityMaster cityMaster;
     private String loginId;
     private String password;
     private String uname;
     private boolean gender;
     private String address;
     private int zipcode;
     private String email;
     private String contact;
     private boolean userStatus;
     private Date userDate;
     private Set bookings = new HashSet(0);
     private OtpMaster otpMaster;
     private int stateId;
     
     

    public Users() {
    }

	
    public Users(CityMaster cityMaster, String loginId, String password, String uname, boolean gender, String address, int zipcode, String email, String contact, boolean userStatus, Date userDate) {
        this.cityMaster = cityMaster;
        this.loginId = loginId;
        this.password = password;
        this.uname = uname;
        this.gender = gender;
        this.address = address;
        this.zipcode = zipcode;
        this.email = email;
        this.contact = contact;
        this.userStatus = userStatus;
        this.userDate = userDate;
    }
    public Users(CityMaster cityMaster, String loginId, String password, String uname, boolean gender, String address, int zipcode, String email, String contact, boolean userStatus, Date userDate, Set bookings, OtpMaster otpMaster) {
       this.cityMaster = cityMaster;
       this.loginId = loginId;
       this.password = password;
       this.uname = uname;
       this.gender = gender;
       this.address = address;
       this.zipcode = zipcode;
       this.email = email;
       this.contact = contact;
       this.userStatus = userStatus;
       this.userDate = userDate;
       this.bookings = bookings;
       this.otpMaster = otpMaster;
    }

    public int getStateId() {
        return stateId;
    }

    public void setStateId(int stateId) {
        this.stateId = stateId;
    }
   
    
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public CityMaster getCityMaster() {
        return this.cityMaster;
    }
    
    public void setCityMaster(CityMaster cityMaster) {
        this.cityMaster = cityMaster;
    }
    public String getLoginId() {
        return this.loginId;
    }
    
    public void setLoginId(String loginId) {
        this.loginId = loginId;
    }
    public String getPassword() {
        return this.password;
    }
    
    public void setPassword(String password) {
        this.password = password;
    }
    public String getUname() {
        return this.uname;
    }
    
    public void setUname(String uname) {
        this.uname = uname;
    }
    public boolean isGender() {
        return this.gender;
    }
    
    public void setGender(boolean gender) {
        this.gender = gender;
    }
    public String getAddress() {
        return this.address;
    }
    
    public void setAddress(String address) {
        this.address = address;
    }
    public int getZipcode() {
        return this.zipcode;
    }
    
    public void setZipcode(int zipcode) {
        this.zipcode = zipcode;
    }
    public String getEmail() {
        return this.email;
    }
    
    public void setEmail(String email) {
        this.email = email;
    }
    public String getContact() {
        return this.contact;
    }
    
    public void setContact(String contact) {
        this.contact = contact;
    }
    public boolean isUserStatus() {
        return this.userStatus;
    }
    
    public void setUserStatus(boolean userStatus) {
        this.userStatus = userStatus;
    }
    public Date getUserDate() {
        return this.userDate;
    }
    
    public void setUserDate(Date userDate) {
        this.userDate = userDate;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }
    public OtpMaster getOtpMaster() {
        return this.otpMaster;
    }
    
    public void setOtpMaster(OtpMaster otpMaster) {
        this.otpMaster = otpMaster;
    }
}


