package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.List;
import java.util.Set;
import org.springframework.web.multipart.MultipartFile;

/**
 * Venue generated by hbm2java
 */
public class Venue  implements java.io.Serializable {


     private Integer venueId;
     private CitySport citySport;
     private String venueName;
     private String venueAddress;
     private String img1;
     private String img2;
     private String img3;
     private String area;
     private int capacity;
     private float price;
     private boolean venueStatus;
     private Date venueDate;
     private String venueDescription;
     private Set venueSports = new HashSet(0);
     private List<MultipartFile> image1;
     private List<MultipartFile> image2;
     private List<MultipartFile> image3;

    public List<MultipartFile> getImage1() {
     return image1;
    }

    public void setImage1(List<MultipartFile> image1) {
     this.image1 = image1;
    }

    public List<MultipartFile> getImage2() {
        return image2;
    }

    public void setImage2(List<MultipartFile> image2) {
        this.image2 = image2;
    }

    public List<MultipartFile> getImage3() {
        return image3;
    }

    public void setImage3(List<MultipartFile> image3) {
        this.image3 = image3;
    }
          
    public Venue() {
    }
	
    public Venue(CitySport citySport, String venueName, String venueAddress, String img1, String img2, String img3, String area, int capacity, float price, boolean venueStatus, Date venueDate, String venueDescription) {
        this.citySport = citySport;
        this.venueName = venueName;
        this.venueAddress = venueAddress;
        this.img1 = img1;
        this.img2 = img2;
        this.img3 = img3;
        this.area = area;
        this.capacity = capacity;
        this.price = price;
        this.venueStatus = venueStatus;
        this.venueDate = venueDate;
        this.venueDescription = venueDescription;
    }
    public Venue(CitySport citySport, String venueName, String venueAddress, String img1, String img2, String img3, String area, int capacity, float price, boolean venueStatus, Date venueDate, String venueDescription, Set venueSports) {
       this.citySport = citySport;
       this.venueName = venueName;
       this.venueAddress = venueAddress;
       this.img1 = img1;
       this.img2 = img2;
       this.img3 = img3;
       this.area = area;
       this.capacity = capacity;
       this.price = price;
       this.venueStatus = venueStatus;
       this.venueDate = venueDate;
       this.venueDescription = venueDescription;
       this.venueSports = venueSports;
    }
    
    public Integer getVenueId() {
        return this.venueId;
    }
    
    public void setVenueId(Integer venueId) {
        this.venueId = venueId;
    }
    public CitySport getCitySport() {
        return this.citySport;
    }
    
    public void setCitySport(CitySport citySport) {
        this.citySport = citySport;
    }
    public String getVenueName() {
        return this.venueName;
    }
    
    public void setVenueName(String venueName) {
        this.venueName = venueName;
    }
    public String getVenueAddress() {
        return this.venueAddress;
    }
    
    public void setVenueAddress(String venueAddress) {
        this.venueAddress = venueAddress;
    }
    public String getImg1() {
        return this.img1;
    }
    
    public void setImg1(String img1) {
        this.img1 = img1;
    }
    public String getImg2() {
        return this.img2;
    }
    
    public void setImg2(String img2) {
        this.img2 = img2;
    }
    public String getImg3() {
        return this.img3;
    }
    
    public void setImg3(String img3) {
        this.img3 = img3;
    }
    public String getArea() {
        return this.area;
    }
    
    public void setArea(String area) {
        this.area = area;
    }
    public int getCapacity() {
        return this.capacity;
    }
    
    public void setCapacity(int capacity) {
        this.capacity = capacity;
    }
    public float getPrice() {
        return this.price;
    }
    
    public void setPrice(float price) {
        this.price = price;
    }
    public boolean isVenueStatus() {
        return this.venueStatus;
    }
    
    public void setVenueStatus(boolean venueStatus) {
        this.venueStatus = venueStatus;
    }
    public Date getVenueDate() {
        return this.venueDate;
    }
    
    public void setVenueDate(Date venueDate) {
        this.venueDate = venueDate;
    }
    public String getVenueDescription() {
        return this.venueDescription;
    }
    
    public void setVenueDescription(String venueDescription) {
        this.venueDescription = venueDescription;
    }
    public Set getVenueSports() {
        return this.venueSports;
    }
    
    public void setVenueSports(Set venueSports) {
        this.venueSports = venueSports;
    }
}


