package dto;
// Generated Aug 16, 2017 12:27:59 AM by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * VenueSport generated by hbm2java
 */
public class VenueSport  implements java.io.Serializable {


     private Integer id;
     private Sport sport;
     private Venue venue;
     private Set bookings = new HashSet(0);

    public VenueSport() {
    }

    public VenueSport(Sport sport, Venue venue, Set bookings) {
       this.sport = sport;
       this.venue = venue;
       this.bookings = bookings;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public Sport getSport() {
        return this.sport;
    }
    
    public void setSport(Sport sport) {
        this.sport = sport;
    }
    public Venue getVenue() {
        return this.venue;
    }
    
    public void setVenue(Venue venue) {
        this.venue = venue;
    }
    public Set getBookings() {
        return this.bookings;
    }
    
    public void setBookings(Set bookings) {
        this.bookings = bookings;
    }
}


